src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School_ID__c</fullName>
        <externalId>true</externalId>
        <label>School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Id__c</fullName>
        <formula>IF(ISNULL(SD_ID__c),
Account.School_ID__c,
23)</formula>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Form__c.object
<CustomObject>
    <fields>
        <fullName>Recruitment_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruitment Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Forms</relationshipLabel>
        <relationshipName>Sales_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Form</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Sales Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Form</label>
        <referenceTo>Sales_Form__c</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacancy_Employer__c</fullName>
        <label>Employer School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewAccountVacancyLinker.cls
/**
 * Linker class for processing a list of new accounts Accounts and linking orphan vacancies.
 */
public with sharing class NewAccountVacancyLinker {
	
	private Map<Double, Account> accountsBySchoolId;
	private List<Vacancy__c> vacanciesThatMatch;
	
   /**
	* Creates the object based on the given accounts.
	* Maps and gathers all the data needed for the procesing.
	*/
	public NewAccountVacancyLinker(List<Account> updatedAccounts) {
				System.debug('Updated Accounts ' + updatedAccounts);
		
		this.accountsBySchoolId = mapAccountsBySchoolId(updatedAccounts);
		this.vacanciesThatMatch = queryAllVacanciesForSchoolIds(
			accountsBySchoolId.keySet());
		System.debug('The following vacancies match the schoolId (' + updatedAccounts + '): '  + vacanciesThatMatch);
			
	}
   
   /**
	* For all vacancies that match the account's schoolId we set:
	* vacancy->account = the new account
	* vacancy->Sales Form->Recruitment Owner->Account = the new account
	*/	
	public void linkVacanciesAndContacts() {
		linkToVacanciesWithSameSchoolId();
		linkToContactsFromThoseVacancyForms();
	}
	
	private void linkToVacanciesWithSameSchoolId() {
		for (Vacancy__c vacancy : vacanciesThatMatch) {
			Account accToMatch = accountsBySchoolId.get(
				vacancy.Vacancy_Employer__c);
			vacancy.Account__c = accToMatch.Id;
		}
		update vacanciesThatMatch;
	}
	
	private Map<Double, Account> mapAccountsBySchoolId(List<Account> accounts) {
		Map<Double, Account> result = new Map<Double, Account>();
		
		for (Account acc : accounts) {
			result.put(acc.School_Id__c, acc);
		}
		
		return result;
	}
	
	private void linkToContactsFromThoseVacancyForms() {
		
		List<Contact> contactsToUpdateAccount = new List<Contact>();
		for (Vacancy__c vacancy : vacanciesThatMatch) {
			Account accToMatch = accountsBySchoolId.get(vacancy.Vacancy_Employer__c);
			
			if (hasSalesForm(vacancy) && hasRecruitmentOwner(vacancy.Sales_Form__r)) {
				System.debug('Contact to update = ' +  vacancy.Sales_Form__r.Recruitment_Owner__c);
				
				Contact updatedContact = new Contact(
										Id = vacancy.Sales_Form__r.Recruitment_Owner__c,
										accountId = accToMatch.Id);
										
				contactsToUpdateAccount.add(updatedContact);
			}
		}
		
		update contactsToUpdateAccount;
	}
	
	private List<Vacancy__c> queryAllVacanciesForSchoolIds(Set<Double> schoolIds) {
		return [SELECT 
					id, 
					Vacancy_Employer__c, 
					Account__c,
					Sales_Form__r.Recruitment_Owner__r.AccountId
				FROM Vacancy__c
				WHERE Account__c = NULL
				AND Vacancy_Employer__c != NULL
				AND Vacancy_Employer__c IN :schoolIds];
	}
	
	private Boolean hasSalesForm(Vacancy__c vacancy) {
		return vacancy.Sales_Form__r != null;
	}
	
	private Boolean hasRecruitmentOwner(Sales_Form__c salesForm) {
		return salesForm.Recruitment_Owner__c != null;
	}

}