src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_ID__c</fullName>
        <externalId>true</externalId>
        <label>School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <label>Ad Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.Name</field>
                <operation>equals</operation>
                <value>MSL Booking</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Call_Date__c</fullName>
        <label>Customer Care Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Id__c</fullName>
        <formula>IF(ISNULL(SD_ID__c),
Account.School_ID__c,
23)</formula>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Available_Values__c</fullName>
        <inlineHelpText>Available values for a particular metric that users can choose from. Please have each value in a separate line.</inlineHelpText>
        <label>Available Values</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Satisfaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Call_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Care Call Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Metrics_Question__c</fullName>
        <label>Metrics Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Format__c</fullName>
        <inlineHelpText>The type of question format the user wants to have in the survey (e.g. Free Textbox, Multiple Choice, Rating, etc.).</inlineHelpText>
        <label>Question Format</label>
        <picklist>
            <picklistValues>
                <fullName>Free Textbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Choice (One Answer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Choice (Multiple Answers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Numeric Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Weight__c</fullName>
        <inlineHelpText>The number associate to the specific answer associated with this question. Please have each value in a separate line.</inlineHelpText>
        <label>Response Weight</label>
        <type>TextArea</type>
    </fields>
    <label>Metrics</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Metrics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <description>Booking Reference Number</description>
        <externalId>true</externalId>
        <label>Ad Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Form__c.object
<CustomObject>
    <fields>
        <fullName>Ad_Insert_MSL_Id__c</fullName>
        <label>MSL Ad Insert Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MSL_Ad_Number__c</fullName>
        <label>MSL Ad Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recruitment_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruitment Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Forms</relationshipLabel>
        <relationshipName>Sales_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesperson_Name__c</fullName>
        <label>Salesperson</label>
        <picklist>
            <picklistValues>
                <fullName>Adrian Munro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aled Evans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alex Hughes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alison Brady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amar  Dhanjan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ben Rawson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claire Neary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hannah Dedman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jemima Greenacre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jessica Marshall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jimmy Jobson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kaan Ibrahim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Martin Bennett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ross Mitchell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sean Marsh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Thurston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tom Shillabeer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tracy  Laverack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viv Aylward</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Form</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Sales Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Metrics__c.object
<CustomObject>
    <fields>
        <fullName>Metrics__c</fullName>
        <label>Metrics</label>
        <referenceTo>Metrics__c</referenceTo>
        <relationshipLabel>Survey Metrics</relationshipLabel>
        <relationshipName>Survey_Metrics</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Weight__c</fullName>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Template__c</fullName>
        <label>Survey Template</label>
        <referenceTo>Survey_Template__c</referenceTo>
        <relationshipLabel>Survey Metrics</relationshipLabel>
        <relationshipName>Survey_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Metrics</label>
    <nameField>
        <displayFormat>SM-{0000000000}</displayFormat>
        <label>Survey Metrics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Template__c.object
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ad_Insert_MSL_ID__c</fullName>
        <externalId>true</externalId>
        <label>Ad Insert MSL ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <label>Ad Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Call_Date__c</fullName>
        <inlineHelpText>6 weeks after the ad has expired in the TES website. If the date falls on a Saturday or Sunday, the date would be on the Friday before those days.</inlineHelpText>
        <label>Customer Care Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Form</label>
        <referenceTo>Sales_Form__c</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Class_Text__c</fullName>
        <label>Sub Class Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vacancy_Employer__c</fullName>
        <label>Employer School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vacancy_Position_and_Subject__c</fullName>
        <label>Sub Class Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCCEmailArchiveService.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
global class TestCCEmailArchiveService {
	
	/*global static String testMessage = '{ "uuid":"1111", "subject":"test subject", "account_email_address": "test@tesglobal.com", "tes_mailbox_address": "international@tesglobal.com", "body":"test message body", "message_id":"id0000", "references_header":"aaa", "recieveDate":"0" }';
	
	global class EmailArchiveServiceMock implements HttpCalloutMock {
		global HTTPResponse respond(HTTPRequest req) {
			String endpoint = req.getEndpoint();
			String[] paramList = null;
			if(endpoint.indexOf('?') == -1) {
				paramList = req.getBody().split('&');
			} else {
				paramList = endpoint.substring(endpoint.indexOf('?')+1).split('&');
			}
			Id oppId = null;
			for(String param : paramList) {
				if(param.startsWith('oppId')) {
					oppId = param.substring(6);
				}
			}
			
			Opportunity opp = [select Name from Opportunity where Id = :oppId];
			HttpResponse res = new HttpResponse();
	        res.setHeader('Content-Type', 'application/json');
	        if(paramList.size() == 1) {
		        if(opp.Name == 'Test Booking OK') {
		        	res.setBody('[ '+testMessage+' ]');
		        } else if(opp.Name == 'Test Booking EX') {
		        	res.setBody('{ [ { aaaa } ] }');
		        }
	        } else if(paramList.size() == 2) {
	        	if(paramList[1].startsWith('pos') && paramList[1].indexOf('FIRST') != -1) {
	        		if(opp.Name == 'Test Booking OK') {
	        			res.setBody(testMessage);
	        		}
	        	}
	        } else if(paramList.size() == 3) {
	        	res.setBody('true');
	        }
	        res.setStatusCode(200);
	        return res;
    	}
	}
	/*
    @isTest(SeeAllData=false)
	public static void testAttachments() {
		Test.setMock(HttpCalloutMock.class, new EmailArchiveServiceMock());
		
		test.startTest();

        // Testing attachments
        service.searchAttachments('searchText', 1);
        
		test.stopTest();
	}
    
    @isTest(SeeAllData=false)
	public static void testListMessages() {
		Test.setMock(HttpCalloutMock.class, new EmailArchiveServiceMock());
		
		//test an opportunity id which will return a single item.
		Opportunity opp = new Opportunity(Name = 'Test Booking OK', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		Opportunity oppKo = new Opportunity(Name = 'Test Booking KO', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		insert new Opportunity[] { opp, oppKo };
		
		test.startTest();
		CCEmailArchiveService service = new CCEmailArchiveService();
		List<TESMessage> messageList = service.listMesssages(opp.Id);
		System.assertEquals(1,messageList.size());
		messageList = service.listMesssages(oppKo.Id);
		System.assertEquals(0,messageList.size());
		
		//we need to test the getFirstMessage method
		TESMessage firstMessage = service.getFirstMessage(opp.Id);
		System.assertEquals('1111',firstMessage.uuid);
		firstMessage = service.getFirstMessage(oppKo.Id);
		System.assertEquals(null,firstMessage);
		//we need to test the moveMessage method
		service.moveMessage('1111',opp.Id);

		test.stopTest();
	}
	
	@isTest(SeeAllData=false)
	public static void testTESMessage() {
		test.startTest();
		TESMessage msg = new TESMessage();
		msg.uuid = '1111';
		msg.subject = 'Test Subject';
		msg.account_email_address = 'test@tesglobal.com';
		msg.tes_mailbox_address = 'international@tesglobal.com';
		msg.body = 'test body';
		msg.message_id = 'msg0000';
		msg.references_header = 'ref0000';
		msg.recieveDate = Datetime.newInstance(2011,1,1,0,0,0).getTime();
		System.assertEquals(2011,msg.getDate().year());
		System.assertEquals(1,msg.getDate().month());
		System.assertEquals(1,msg.getDate().day());
		test.stopTest();
	}
	
	@isTest(SeeAllData=false)
	public static void testEmailListController() {
		Test.setMock(HttpCalloutMock.class, new EmailArchiveServiceMock());
		
		//test an opportunity id which will return a single item.
		Opportunity opp = new Opportunity(Name = 'Test Booking OK', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		Opportunity oppKo = new Opportunity(Name = 'Test Booking KO', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		Opportunity oppEx = new Opportunity(Name = 'Test Booking EX', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		insert new Opportunity[] { opp, oppKo, oppEx };
		
		test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(opp);
		CCEmailListController listController = new CCEmailListController(sc);
		//test the getMessagesAsJson method
		String jsonMessageList = listController.getMessagesAsJson();
		System.assertNotEquals(null,jsonMessageList);
		//test the getMessageBody method
		String messageBody = CCEmailListController.getMessageBody('1111',jsonMessageList);
		System.assertEquals('test message body',messageBody);
		messageBody = CCEmailListController.getMessageBody('0000',jsonMessageList);
		System.assertEquals(null,messageBody);
		
		sc = new ApexPages.StandardController(oppEx);
		listController = new CCEmailListController(sc);
		test.stopTest();
	}*/
	
	@isTest(SeeAllData=false)
	public static void testCustomerSuccessController() {
		Account a = new Account(Name = 'Test Account', School_Id__c=1234567, Region__c = 'London');
		insert a;
		
		Contact ct = new Contact(FirstName = 'Chris', LastName = 'Stura', Phone = '0000', AccountId = a.Id, email = 'test@test.com', Salutation = 'Mr.');
		Contact ctNoVc = new Contact(FirstName = 'Alan', LastName = 'No Vacancy Contact', Phone = '0001', AccountId = a.Id, email = 'novc@test.com', Salutation = 'Mr.');
		insert new Contact[] { ct, ctNoVc };
		
		Survey_Template__c  surveyTemplate = new Survey_Template__c(Name = 'Mid-Campaign Check-In');
		insert surveyTemplate;
		
		Survey_Template__c twoMinuteSurvey = new Survey_Template__c(Name = 'TES Recruitment Two Minute Survey');
		insert twoMinuteSurvey;
		
		//add some survey metrics for test
		Metrics__c metric1 = new Metrics__c(Available_Values__c = 'Value 1\nValue 2', Category__c = 'Customer Satisfaction',
											Customer_Care_Call_Date__c = false, Metrics_Question__c = 'Question 1',
											Question_Format__c = 'Multiple Choice (One Answer)', Response_Weight__c = '10,20');
		insert metric1;
		
		Survey_Metrics__c surveyMetric1 = new Survey_Metrics__c(Metrics__c = metric1.Id, Order__c = 1, Question_Weight__c = 10, Survey_Template__c = surveyTemplate.Id);
		
		insert surveyMetric1;
		
		surveyMetric1 = [select Id,Name,Metrics__c,Order__c,Question_Weight__c,Survey_Template__c from Survey_Metrics__c where Id = :surveyMetric1.Id];
		
		//we need to add a fake vacancy object here.
		Opportunity opp = new Opportunity(Name = 'Test Booking OK', StageName = 'TBD', CloseDate = Date.newInstance(2011,1,1));
		insert opp;
		
		Sales_Form__c sf = new Sales_Form__c(MSL_Ad_Number__c = '0000', Salesperson_Name__c = 'Adrian Munro', Recruitment_Owner__c = ct.Id);
		Sales_Form__c sf1 = new Sales_Form__c(Ad_Insert_MSL_ID__c = '0000', Salesperson_Name__c = 'Adrian Munro', Recruitment_Owner__c = ct.Id);
		insert new Sales_Form__c[] { sf, sf1 };
		
		Vacancy__c v = new Vacancy__c(Name = 'Head Teacher', Booking__c = opp.Id, Vacancy_Position_and_Subject__c = '09', 
									  Sub_Class_Text__c = 'TAX', Ad_Insert_MSL_ID__c = '0000', Ad_Number__c = '0000', Account__c = a.Id, Vacancy_Employer__c=1234567);
		
		insert v;
		
		Case nonSurveyCase = new Case(Subject = 'Case number 1', Contact_Email__c = 'diego.villatora@thisisatest.com', 
                                   Contact_Phone__c = '08328810930');
		insert nonSurveyCase;
		
		Case c = [select Id,Vacancy__c from Case where Vacancy__c = :v.Id];
		
		test.startTest();
        
		ApexPages.StandardController sc = new ApexPages.StandardController(c);
		CustomerSuccessSurveyController surveyController = new CustomerSuccessSurveyController(sc);
		
		//test the getTemplatesAsOptions method
		List<SelectOption> options = surveyController.getTemplatesAsOptions();
		System.assertEquals(2,options.size());
		
		//test the parseValues method
		List<String> valueList = surveyController.parseValues('option 1\noption2');
		System.assertEquals(2,valueList.size()); 
		System.assertEquals(null,surveyController.parseValues(null));
		System.assertEquals(null,surveyController.getTemplateById(ct.Id));
		System.assertEquals(1,surveyController.listVacancyContacts().size());
		System.assertEquals(1,surveyController.getVacancyContacts().size());
		System.assertNotEquals(null,CustomerSuccessSurveyController.getVacancyContactById(ct.Id,c.Id));
		System.assertEquals(null,CustomerSuccessSurveyController.getVacancyContactById(c.Id,c.Id));
		System.assertEquals(1,surveyController.getVacancyContactForSurvey(ct.Id).size());
		System.assertNotEquals(null,surveyController.doCancel());
		surveyController.closePopup();
		surveyController.showPopup();
		surveyController.closeHelpPopup();
		surveyController.showHelpPopup();
		System.assertNotEquals(null,surveyController.getTemplateById(surveyTemplate.Id));
		System.assertEquals(true,CustomerSuccessSurveyController.saveSurvey(c.Id,surveyTemplate.Id,'{ "values" : [ { "key": "'+surveyMetric1.Name+'", "value": "value1" } ] }',ct.Id,true));
		System.assertEquals(false,CustomerSuccessSurveyController.saveSurvey(c.Id,surveyTemplate.Id,'{ "values" : [] }',ct.Id,true));
		System.assertEquals(false,CustomerSuccessSurveyController.saveSurvey(c.Id,twoMinuteSurvey.Id,'{ "values" : [] }',ct.Id,true));
		System.assertEquals(false,CustomerSuccessSurveyController.saveSurvey(c.Id,c.Id,'{ "values" : [] }',ct.Id,true));
		System.assertNotEquals(null,CustomerSuccessSurveyController.getInstanceName());
		System.assertEquals(true,CustomerSuccessSurveyController.sendSurvey(c.id,surveyTemplate.Id,ct.Id));
		
		//we now have to test creating a new contact
		System.assertEquals(null,CustomerSuccessSurveyController.createContact(nonSurveyCase.Id,'Mr.','Morgan','Now VC Contact','novc@test.com','0001'));
		System.assertEquals(ctNoVc.Id,CustomerSuccessSurveyController.createContact(c.Id,'Mr.','Morgan','Now VC Contact','novc@test.com','0001').Id);
		System.assertEquals(ct.Id,CustomerSuccessSurveyController.createContact(c.Id,'Mr.','Morgan','Now VC Contact','test@test.com','0001').Id);
		//System.assertNotEquals(null,CustomerSuccessSurveyController.createContact(c.Id,'Mr.','Morgan','Now VC Contact','test2@test.com','0001'));
		
		PageReference pageRef = new PageReference('/'+c.Id);
        pageRef.getParameters().put('survey', surveyTemplate.Id);
        pageRef.getParameters().put('contact', ct.Id);
        Test.setCurrentPage(pageRef);
        
        surveyController = new CustomerSuccessSurveyController(sc);
        
		test.stopTest();
	}
}