src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City_Town__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ag. Lge non-PPA/NPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Med non-PPA/NPA 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Sml non-PPA/NPA 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency NPA/PPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency PPA Mem. 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency UK Major 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 25%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 27.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 30%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Analysed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ABKHAZIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKROTIRI AND DHEKELIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALAND ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASHMORE AND CARTIER ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES, AUTONOMOUS REGION OF THE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <picklist>
            <controllingField>Client_Type__c</controllingField>
            <picklistValues>
                <fullName>Academy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further/Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ind. Prepatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent MultiPhase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent PrePrep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intra Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Education Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Phase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Limited Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Reg. Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLC Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pupil Referral Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Email__c</fullName>
        <inlineHelpText>The email that gets populated on the client record in MSL. Generally, the Finance/Billing email of the client.</inlineHelpText>
        <label>MSL Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_Approved_by_Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_1__c</fullName>
        <label>Region 1</label>
        <picklist>
            <picklistValues>
                <fullName>Classified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region_2__c</fullName>
        <label>Region 2</label>
        <picklist>
            <controllingField>Region_1__c</controllingField>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Form__c.object
<CustomObject>
    <fields>
        <fullName>Ad_Insert_MSL_Id__c</fullName>
        <label>MSL Ad Insert Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesperson_Name__c</fullName>
        <label>Salesperson</label>
        <picklist>
            <picklistValues>
                <fullName>Adrian Munro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aled Evans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alex Hughes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alison Brady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amar  Dhanjan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ben Rawson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claire Neary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hannah Dedman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jemima Greenacre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jessica Marshall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jimmy Jobson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kaan Ibrahim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Martin Bennett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ross Mitchell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sean Marsh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Thurston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tom Shillabeer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tracy  Laverack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viv Aylward</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Form</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Sales Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testSFormController.cls
@isTest

public class testSFormController {
    
    public static testMethod void testSFormController() {

        Account acc = new Account (Name = 'test',
                                   Client_Type__c = 'To Be Analysed',
                                   Customer_Group__c = 'Academy',
                                   Phone = '1231231231',
                                   Street__c = '123123',
                                   City_Town__c = 'test',
                                   Country__c = 'Uganda',
                                   Post_Code__c = '12333',
                                   Main_Email__c = 'dsadsa@dsadsa.com',
                                   Region_1__c = 'Classified',
                                   Region_2__c = 'International',
                                   Not_Approved_by_Finance__c = false);
        
        insert acc;
        
        
        Sales_Form__c sf = new Sales_Form__c (Salesperson_Name__c = 'Claire Neary',
                                              Ad_Insert_MSL_Id__c = '9990120001',
                                              Sales_Notes__c = 'Testing',
                                              Recruitment_Owner__c = null);
        
        RecordType cRecType = [SELECT Id FROM RecordType WHERE sObjectType = 'Contact' AND Name = 'Customer Success'];
        
        Contact c = new Contact(LastName = 'Smith', 
                                Phone = '123123123', 
                                Email = 'something@something.com', 
                                AccountId = acc.Id,
                                RecordTypeId = cRecType.Id,
                                Salutation = 'Ms.');
        
       PageReference pg = Page.sForm;
       Test.setCurrentPage(pg); 
       
       ApexPages.StandardController ctrl = new ApexPages.StandardController(sf);
       sFormController ext = new sFormController(ctrl);

        PageReference savePage = ext.saveAndRedirect();
        
        ext.sForm = sf;
        
        insert ext.sForm;
         
        ext.contact = c;
        
        if(ext.sForm.Recruitment_Owner__c == null) {
        insert ext.contact;
        }
        
        ext.sFormstoUpdate = [SELECT Id, Recruitment_Owner__c FROM Sales_Form__c WHERE Recruitment_Owner__c = null AND Id =: ext.sForm.Id ];
        ext.sFormsToUpdate.Recruitment_Owner__c = ext.contact.Id;
        
        
        update ext.sFormstoUpdate;
        
        system.assertEquals('Claire Neary', sf.Salesperson_Name__c);
        system.assertEquals('9990120001', sf.Ad_Insert_MSL_Id__c);
        system.assertEquals('Testing', sf.Sales_Notes__c);
        system.assertEquals(ext.contact.Id, ext.sFormsToUpdate.Recruitment_Owner__c);
        
        
        //system.assertEquals(Page.salesFormThanks, savePage);
      
        PageReference returnPage = ext.returnToForm();
        
        system.assertEquals('/apex/sForm', returnPage.getUrl());
        
        
        
        
        
        
        
        
        
    }
    
}