src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ag. Lge non-PPA/NPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Med non-PPA/NPA 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Sml non-PPA/NPA 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency NPA/PPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency PPA Mem. 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency UK Major 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 25%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 27.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 30%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Analysed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <label>Contact Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Main_Reason_for_Complaint__c</fullName>
        <label>Main Reason for Complaint</label>
        <picklist>
            <picklistValues>
                <fullName>Advert Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booking Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount/Upgrade Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Advert/Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice/Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing/Rating Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Related to Customer Success Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_Complaint__c</fullName>
        <label>Reason for Complaint</label>
        <picklist>
            <controllingField>Main_Reason_for_Complaint__c</controllingField>
            <picklistValues>
                <fullName>100% Run to Fill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15% Repeat Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15% Repeat Discount (Print)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15% Repeat Discount (Web)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Appeared Early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Appeared Late</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Cancelled (Additional Module)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Cancelled (Print)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Cancelled (Web)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Did Not Appear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Not Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Discount 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Discount 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Discount 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Discount 17.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Incentive Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Discount 10% Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Discount 12.5% Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Agency Commission Omitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Advert (Additional Module)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Advert (Print)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Advert (Web)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Invoice (System Error)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Primary+ Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Web Gold Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error (Print &amp; Web)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error on Print Advert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error on Web Advert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardsell Tactics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reported_By_Team__c</fullName>
        <label>Reported By (Team)</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell P&amp;O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reported_By__c</fullName>
        <label>Reported By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>School_Institution__c</fullName>
        <label>School/Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Complaints</fullName>
        <active>true</active>
        <businessProcess>Complaints Process</businessProcess>
        <description>Case record type used to record any complaints from customers</description>
        <label>Complaints</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestComplaintsFormController.cls
@isTest

public class TestComplaintsFormController {
    
    public static testMethod void TestComplaintsFormController() {
        
        RecordType complaintsRT = [SELECT Id from RecordType WHERE sObjectType = 'Case' AND Name = 'Complaints']; 
        
        //insert new cases
        List<Case> newCases = new List<Case>();
        for(Integer i=0; i < 100; i++) {    
            
            Case cs = new Case(
                RecordTypeId = complaintsRt.Id,
                Salutation__c = 'ms.',
                School_Institution__c = 'test school',
                Contact_Last_Name__c = 'smith',
                Contact_Email__c = 'smith@dsadsa.com',
                Contact_Phone__c = '3213123',
                Reason_for_Complaint__c = 'Booking Error',
                Description = 'test',
                Main_Reason_for_Complaint__c = 'test',
                Reported_By__c = 'test',
            	Reported_By_Team__c = 'test'
            );
            
             newCases.add(cs);
            
        }
            
            insert newCases;
        
        //insert account
        Account acc = new Account(Name='Test Account',
                                  Client_Type__c = 'To Be Analysed',
                                  Customer_Group__c = 'Academy',
                                  Street__c = '29 Darling',
                                  City_Town__c = 'Boston',
                                  Country__c = 'UGANDA',
                                  Post_Code__c = '312312',
                                  Phone = '123231231',
                                  Main_Email__c = 'dsadsa@dsadsa.com',
                                  Region_1__c = 'Classified',
                                  Region_2__c = 'United Kingdom',
                                  Not_Approved_by_Finance__c = false);
        
        insert acc;

        
        //update case with account
        for(Case c : newCases) {
            c.AccountId = acc.Id;
        }
        
        update newCases;
        

            PageReference pg = Page.CaseFormIntl;
            Test.setCurrentPage(pg); 
            
            ApexPages.StandardSetController setCtrl = new ApexPages.StandardSetController(newCases);
            ComplaintsFormController ext = new ComplaintsFormController(setCtrl);
            
            PageReference saveComplaintInternal = ext.saveComplaintInternal();
        
            PageReference saveComplaint = ext.saveComplaint();
        
            PageReference setCaseTypetoComplaint = ext.setCaseTypetoComplaint();
        
            PageReference setCaseTypetoQuery = ext.setCaseTypetoQuery();
        
            PageReference setCaseTypetoComment = ext.setCaseTypetoComment();
        
            PageReference complaintsForm = ext.complaintsForm();
        
            PageReference complaintsFormIntl = ext.complaintsFormIntl();

 
        }
        
    }