src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Town__c</fullName>
        <label>City/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ag. Lge non-PPA/NPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Med non-PPA/NPA 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ag. Sml non-PPA/NPA 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Local Authority 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency NPA/PPA 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency PPA Mem. 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency UK Major 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas EU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Overseas NonEU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 12.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 15%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 25%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 27.5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O/seas Ag. NonEU 30%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Analysed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ABKHAZIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKROTIRI AND DHEKELIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALAND ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASHMORE AND CARTIER ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES, AUTONOMOUS REGION OF THE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGANDA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Group__c</fullName>
        <label>Customer Group</label>
        <picklist>
            <controllingField>Client_Type__c</controllingField>
            <picklistValues>
                <fullName>Academy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academy Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further/Higher Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ind. Prepatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent MultiPhase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent PrePrep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent Special</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intra Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Education Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Phase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Limited Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Reg. Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLC Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pupil Referral Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Main_Email__c</fullName>
        <inlineHelpText>The email that gets populated on the client record in MSL. Generally, the Finance/Billing email of the client.</inlineHelpText>
        <label>MSL Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_Approved_by_Finance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_1__c</fullName>
        <label>Region 1</label>
        <picklist>
            <picklistValues>
                <fullName>Classified</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region_2__c</fullName>
        <label>Region 2</label>
        <picklist>
            <controllingField>Region_1__c</controllingField>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>School_ID__c</fullName>
        <externalId>true</externalId>
        <label>School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>organisations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Id__c</fullName>
        <externalId>true</externalId>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestNewAccountOrganisationLinker.cls
@isTest
private class TestNewAccountOrganisationLinker
{
	@isTest static void InsertAnAccountWithSchoolId()
	{
		Country__c con = new Country__c();
		con.Name = 'ESP';
		con.title__c = 'Spain';
		insert con;

		Organisation__c o = new Organisation__c();
		o.Name = 'test';
		o.Address_1__c = 'test';
		o.Postcode__c = 'W2 4RL';
		o.Country__c = con.Id;
		o.County__c = 'Test';
		o.School_Id__c = 12345;
		insert o;

		// Insert the Account record.
		Account acc = new Account(Name = 'Test Account',
		                          Client_Type__c = 'To Be Analysed',
		                          Customer_Group__c = 'Academy',
		                          Street__c = '29 Darling',
		                          City_Town__c = 'Boston',
		                          Country__c = 'UGANDA',
		                          Post_Code__c = '312312',
		                          Phone = '123231231',
		                          Main_Email__c = 'dsadsa@dsadsa.com',
		                          Region_1__c = 'Classified',
		                          Region_2__c = 'United Kingdom',
		                          Not_Approved_by_Finance__c = false,
		                          School_ID__c = 12345);

		Test.startTest();
		insert acc;
		Test.stopTest();
	}

	@isTest static void UpdateAnAccountWithSchoolId1()
	{
		Country__c con = new Country__c();
		con.Name = 'ESP';
		con.title__c = 'Spain';
		insert con;

		Organisation__c o1 = new Organisation__c();
		o1.Name = 'test';
		o1.Address_1__c = 'test';
		o1.Postcode__c = 'W2 4RL';
		o1.Country__c = con.Id;
		o1.County__c = 'Test';
		o1.School_Id__c = 1234;
		insert o1;

		Organisation__c o2 = new Organisation__c();
		o2.Name = 'test';
		o2.Address_1__c = 'test';
		o2.Postcode__c = 'W2 4RL';
		o2.Country__c = con.Id;
		o2.County__c = 'Test';
		o2.School_Id__c = 12345;
		insert o2;

		// Insert the Account record.
		Account acc = new Account(Name = 'Test Account',
		                          Client_Type__c = 'To Be Analysed',
		                          Customer_Group__c = 'Academy',
		                          Street__c = '29 Darling',
		                          City_Town__c = 'Boston',
		                          Country__c = 'UGANDA',
		                          Post_Code__c = '312312',
		                          Phone = '123231231',
		                          Main_Email__c = 'dsadsa@dsadsa.com',
		                          Region_1__c = 'Classified',
		                          Region_2__c = 'United Kingdom',
		                          Not_Approved_by_Finance__c = false,
		                          School_ID__c = 1234);

		insert acc;

		Test.startTest();
		acc.School_ID__c = 12345;
		update acc;
		Test.stopTest();
	}

	@isTest static void UpdateAnAccountWithoutSchoolid()
	{
		Country__c con = new Country__c();
		con.Name = 'ESP';
		con.title__c = 'Spain';
		insert con;

		Organisation__c o1 = new Organisation__c();
		o1.Name = 'test';
		o1.Address_1__c = 'test';
		o1.Postcode__c = 'W2 4RL';
		o1.Country__c = con.Id;
		o1.County__c = 'Test';
		o1.School_Id__c = 1234;
		insert o1;

		// Insert the Account record.
		Account acc = new Account(Name = 'Test Account',
		                          Client_Type__c = 'To Be Analysed',
		                          Customer_Group__c = 'Academy',
		                          Street__c = '29 Darling',
		                          City_Town__c = 'Boston',
		                          Country__c = 'UGANDA',
		                          Post_Code__c = '312312',
		                          Phone = '123231231',
		                          Main_Email__c = 'dsadsa@dsadsa.com',
		                          Region_1__c = 'Classified',
		                          Region_2__c = 'United Kingdom',
		                          Not_Approved_by_Finance__c = false,
		                          School_ID__c = 1234);

		insert acc;

		Test.startTest();
		acc.School_ID__c = null;
		update acc;
		Test.stopTest();
	}


	@isTest static void UpdateAnAccountWithSchoolid2()
	{
		Country__c con = new Country__c();
		con.Name = 'ESP';
		con.title__c = 'Spain';
		insert con;

		Organisation__c o1 = new Organisation__c();
		o1.Name = 'test';
		o1.Address_1__c = 'test';
		o1.Postcode__c = 'W2 4RL';
		o1.Country__c = con.Id;
		o1.County__c = 'Test';
		o1.School_Id__c = 12345;
		insert o1;

		// Insert the Account record.
		Account acc = new Account(Name = 'Test Account',
		                          Client_Type__c = 'To Be Analysed',
		                          Customer_Group__c = 'Academy',
		                          Street__c = '29 Darling',
		                          City_Town__c = 'Boston',
		                          Country__c = 'UGANDA',
		                          Post_Code__c = '312312',
		                          Phone = '123231231',
		                          Main_Email__c = 'dsadsa@dsadsa.com',
		                          Region_1__c = 'Classified',
		                          Region_2__c = 'United Kingdom',
		                          Not_Approved_by_Finance__c = false,
		                          School_ID__c = 1234);

		insert acc;

		Test.startTest();
		acc.School_ID__c = 12345;
		update acc;
		Test.stopTest();
	}

}