src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School_ID__c</fullName>
        <externalId>true</externalId>
        <label>School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ad_Web_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipName>Ad_Web_Performance_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ad Web Metrics</label>
    <nameField>
        <displayFormat>A{00000000}</displayFormat>
        <label>Ad Web Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Web Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Id__c</fullName>
        <formula>IF(ISNULL(SD_ID__c),
Account.School_ID__c,
23)</formula>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Template__c.object
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacancy_Employer__c</fullName>
        <label>Employer School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vacancy_Position_and_Subject__c</fullName>
        <label>Sub Class Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgenciesReportCompControllerTest.cls
@isTest
private class AgenciesReportCompControllerTest {

	private static Account testAccount;
	private static Contact testContact;
	private static Opportunity testbooking;
	private static Survey_Template__c testSurveyTemplate;
	private static Vacancy__c testVacancy;


	private static void createTestObjects() {
		testAccount = (Account) Reach.SmartFactory.createSObject('Account');
		insert testAccount;

		testContact = (Contact) Reach.SmartFactory.createSObject('Contact');
		testContact.AccountId = testAccount.Id;

		testBooking = (Opportunity) Reach.SmartFactory.createSObject('Opportunity');
		testBooking.AccountId = testAccount.Id;

		insert testContact;
		insert testBooking;

		testSurveyTemplate = new Survey_Template__c();
        testSurveyTemplate.Name = 'TES Recruitment Two Minute Survey';
        insert testSurveyTemplate;

		testVacancy = (Vacancy__c) Reach.SmartFactory.createSObject('Vacancy__c');
		testVacancy.Booking__c = testBooking.Id;
		testVacancy.Vacancy_Position_and_Subject__c = '000';		
		testAccount.School_Id__c = 1234;
		testVacancy.Vacancy_Employer__c = 1234;

		insert testVacancy;
	}


	@isTest
	static void itShouldShowTheRightRecords() {
		// Given
		createTestObjects();

		OpportunityContactRole testOppContRole = 
			new OpportunityContactRole(opportunityId=testBooking.Id, contactId= testContact.Id, Role='Booker');

		insert testOppContRole;

		Ad_Web_Performance__c metric = new Ad_Web_Performance__c();
		metric.Date__c = Date.today().addDays(-1);
		metric.Vacancy__c = testVacancy.Id;
		insert metric;

		// When
		AgenciesReportCompController controller = new AgenciesReportCompController();
		controller.contactId = testContact.Id;
		controller.accountId = testAccount.Id;

		// Then
		System.assert(controller.reportLines != null);
		System.assertEquals(1, controller.reportLines.size());
		System.assertEquals(testVacancy.Id, controller.reportLines.get(0).vacancy.Id);
		System.assertEquals(testOppContRole.id, controller.reportLines.get(0).contactRole.Id);
	}

	@isTest
	static void itShouldNotDisplayRecordIfMetricAddedBeforeLastWeek() {
		// Given
		createTestObjects();

		OpportunityContactRole testOppContRole = 
			new OpportunityContactRole(opportunityId=testBooking.Id, contactId= testContact.Id, Role='Booker');

		insert testOppContRole;

		Ad_Web_Performance__c metric = new Ad_Web_Performance__c();
		metric.Date__c = Date.today().addDays(-8);
		metric.Vacancy__c = testVacancy.Id;
		insert metric;

		// When
		AgenciesReportCompController controller = new AgenciesReportCompController();
		controller.contactId = testContact.Id;
		controller.accountId = testAccount.Id;

		// Then
		System.assert(controller.reportLines == null || controller.reportLines.size() == 0);
	}

	@isTest
	static void itShouldNotDisplayRecordIfContactIsNoBooker() {
		// Given
		createTestObjects();

		OpportunityContactRole testOppContRole = 
			new OpportunityContactRole(opportunityId=testBooking.Id, contactId= testContact.Id, Role='OtherRole');

		insert testOppContRole;

		Ad_Web_Performance__c metric = new Ad_Web_Performance__c();
		metric.Date__c = Date.today().addDays(-1);
		metric.Vacancy__c = testVacancy.Id;
		insert metric;

		// When
		AgenciesReportCompController controller = new AgenciesReportCompController();
		controller.contactId = testContact.Id;
		controller.accountId = testAccount.Id;

		// Then
		System.assert(controller.reportLines == null || controller.reportLines.size() == 0);
	}
}