src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>School_ID__c</fullName>
        <externalId>true</externalId>
        <label>School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>School_Id__c</fullName>
        <formula>IF(ISNULL(SD_ID__c),
Account.School_ID__c,
23)</formula>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Form__c.object
<CustomObject>
    <fields>
        <fullName>MSL_Ad_Number__c</fullName>
        <label>MSL Ad Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recruitment_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruitment Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Forms</relationshipLabel>
        <relationshipName>Sales_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesperson_Name__c</fullName>
        <label>Salesperson</label>
        <picklist>
            <picklistValues>
                <fullName>Adrian Munro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aled Evans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alex Hughes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alison Brady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amar  Dhanjan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ben Rawson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claire Neary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hannah Dedman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jemima Greenacre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jessica Marshall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jimmy Jobson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kaan Ibrahim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Martin Bennett</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ross Mitchell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sean Marsh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simon Thurston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tom Shillabeer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tracy  Laverack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viv Aylward</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Form</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Sales Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Template__c.object
<CustomObject>
    <label>Survey Template</label>
    <nameField>
        <label>Survey Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Form</label>
        <referenceTo>Sales_Form__c</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacancy_Employer__c</fullName>
        <label>Employer School ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vacancy_Position_and_Subject__c</fullName>
        <label>Sub Class Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandlerTest.cls
@isTest
public with sharing class AccountTriggerHandlerTest {
	
	public static testMethod void testInsertAccountWithNoSchoolId() {
		Account testAccount = (Account) Reach.SmartFactory.createSObject('Account');
		
		testAccount.School_Id__c = null;
		
		insert testAccount;
		
	}
	
	public static testMethod void testInsertAccountAndLinkVacancy() {
		Account testAccount = (Account) Reach.SmartFactory.createSObject('Account');
		Vacancy__c testVacancy = (Vacancy__c) Reach.SmartFactory.createSObject('Vacancy__c');
		testVacancy.Vacancy_Position_and_Subject__c = '000';
		Survey_Template__c testSurverTemplate = new Survey_Template__c();
        testSurverTemplate.Name = 'TES Recruitment Two Minute Survey';
        
		//Sales_Form__c testSalesForm = (Sales_Form__c) Reach.SmartFactory.createSObject('Sales_Form__c');
		//Contact testSalesForm = (Contact) Reach.SmartFactory.createSObject('Contact');
		
		testAccount.School_Id__c = 1234;
		
		testVacancy.Vacancy_Employer__c = 1234;

        insert testSurverTemplate;		
		insert testVacancy;
		insert testAccount;
		
		testVacancy = [SELECT Id, Account__c FROM Vacancy__c WHERE id = :testVacancy.Id];
		System.assertEquals(testVacancy.Account__c, testAccount.Id);
		
	}

	
	public static testMethod void testInsertAccountAndLinkContact() {

		
		Account testAccount2 = (Account) Reach.SmartFactory.createSObject('Account');      		
		insert testAccount2;
        
		Contact testContact = (Contact) Reach.SmartFactory.createSObject('Contact');
		testContact.AccountId = testAccount2.Id;
		testContact.Email = 'javier.ciccarelli@cloudreach.co.uk';
		testContact.Salutation = 'Mr';
		testContact.LastName = 'Javier';
		testContact.Phone = '+3123123';
		
		insert testContact;
		
		Sales_Form__c testSalesForm = (Sales_Form__c) Reach.SmartFactory.createSObject('Sales_Form__c');
		testSalesForm.Recruitment_Owner__c = testContact.Id;
		testSalesForm.MSL_Ad_Number__c = '12345';
		testSalesForm.Salesperson_name__c = 'Test Name';
		
		insert testSalesForm;
		
		Survey_Template__c testSurverTemplate = new Survey_Template__c();
        testSurverTemplate.Name = 'TES Recruitment Two Minute Survey';     
        insert testSurverTemplate;
        	
		Vacancy__c testVacancy = (Vacancy__c) Reach.SmartFactory.createSObject('Vacancy__c');
		testVacancy.Vacancy_Position_and_Subject__c = '000';
		testVacancy.Vacancy_Employer__c = 1234;
		testVacancy.Sales_form__c = testSalesForm.Id;
		insert testVacancy;
        
  		Account testAccount = (Account) Reach.SmartFactory.createSObject('Account');
		testAccount.School_Id__c = 1234;
		insert testAccount;
		
		testVacancy = [SELECT Id, Account__c FROM Vacancy__c WHERE id = :testVacancy.Id];
		testContact = [SELECT Id, AccountId FROM Contact WHERE id = :testContact.Id];
		
		System.assertEquals(testVacancy.Account__c, testAccount.Id);
		System.assertEquals(testAccount.Id, testContact.AccountId);
	}

}