src/objects/Ad_Web_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Apply_Clicks__c</fullName>
        <label>Job Apply Clicks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Views__c</fullName>
        <label>Job Views</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipName>Ad_Web_Performance_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ad Web Metrics</label>
    <nameField>
        <displayFormat>A{00000000}</displayFormat>
        <label>Ad Web Metrics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Web Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <description>Booking Reference Number</description>
        <externalId>true</externalId>
        <label>Ad Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <label>Ad Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vacancies</relationshipLabel>
        <relationshipName>Vacancies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Ad_Expiry_on_TES_Global_Site__c</fullName>
        <inlineHelpText>Date/Time of Ad Expiry on TES Global Site</inlineHelpText>
        <label>Ad End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_of_Ad_Publication_on_TES_Site__c</fullName>
        <inlineHelpText>Date of Ad Publication on TES Site</inlineHelpText>
        <label>Ad Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgenciesReportCompController.cls
public class AgenciesReportCompController {

	private Boolean initialised = false;

	public Id accountId {get;
		set {
			if (value == null)
				return;
			accountId = value;
			initialiseReport();
		}
	}

	public Id contactId { get;
		set {
			if (value == null)
				return;
			contactId = value;
			initialiseReport();
		}
	}

	public List<AdStatsReport> reportLines {get;set;}

	private void initialiseReport() {
		//System.debug('accountId: ' + accountId + ' contactId: ' + contactId);
		if (initialised || accountId == null || contactId == null)
			return;

		this.initialised = true;

		List<OpportunityContactRole> contactRoles = [SELECT OpportunityId, Contact.Name 
        												FROM OpportunityContactRole 
        												WHERE Role = 'Booker' 
        													AND ContactId = :contactId
        													 AND Contact.AccountId = :accountId];

        System.debug('Contact roles: ' + contactRoles);

        Map<Object, SObject> contactRoleByOppId = Reach.Utils.collect(contactRoles)
        											.byField(OpportunityContactRole.OpportunityId)
        											.noDuplicates();

        Set<Id> ids = new Set<Id>();
	    for (Object oppId : contactRoleByOppId.keySet())
	        ids.add((Id) oppId);

	    Date filterDate = Date.today().addDays(-7);
	    //filterDate;

        List<Vacancy__c> vcs = [Select Name, Account__c, Date_of_Ad_Publication_on_TES_Site__c, 
	        Date_of_Ad_Expiry_on_TES_Global_Site__c, Ad_Number__c, 
	        Booking__r.Account.Name, Booking__r.Name, Account__r.Name,
	    	(Select Date__c, Job_Views__c, Job_Apply_Clicks__c From Ad_Web_Performance_Data__r WHERE Date__c > :filterDate ORDER BY Date__c DESC)
	   		From Vacancy__c WHERE 
	   			Booking__c IN :ids
	   			AND ID IN (SELECT vacancy__c FROM Ad_Web_Performance__c WHERE Date__c > :filterDate)
	   		];

	   	        System.debug('Vacancies: ' + vcs);

       // List<SObject> filteredVacancies = filterVacanciesThatDontHavePerformanceData

                    

        reportLines = new List<AdStatsReport>();
        for (Vacancy__c vacancy : vcs) {

            AdStatsReport reportLine = new AdStatsReport();
            reportLine.vacancy = vacancy;

            OpportunityContactRole role  = (OpportunityContactRole) contactRoleByOppId.get(vacancy.Booking__c);
            reportLine.contactRole = role;
            reportLines.add(reportLine);
        }


	}

	public class AdStatsReport {
	    public  Vacancy__c vacancy {get; set;}
	    public  OpportunityContactRole contactRole {get; set;}
	}

}