src/objects/Busy_Time_Log__c.object
<CustomObject>
    <description>Object used for bookers to log their unavailable times.</description>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>Please select the date for when you will not be available. Bookings will not be assigned to you during the start and end times for this specific date.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <inlineHelpText>Please select the end time for when you will not be available. Bookings will not be assigned to you during the start and end times.</inlineHelpText>
        <label>End Time</label>
        <picklist>
            <picklistValues>
                <fullName>00:00</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>00:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>00:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23:45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_Unavailability__c</fullName>
        <description>Please specify the reason why you will not be available during these times.</description>
        <inlineHelpText>Please specify the reason why you will not be available during these times.</inlineHelpText>
        <label>Reason for Unavailability</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Please select the start time for when you will not be available. Bookings will not be assigned to you during the start and end times.</inlineHelpText>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>00:00</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>00:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>00:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06:45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07:15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23:45</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person who will be unavailable during the specified start and end times.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Unavailable_Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Busy Time Log</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Busy Time Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Busy Time Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date Ad Web Performance was taken.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Custom__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive to Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined to Engage/No Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, Awaiting Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, No Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Feedback to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Current_Booking_Count__c</fullName>
        <inlineHelpText>The current number of records assigned to a user.</inlineHelpText>
        <label>Current Record Assignment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTF_Booking_Quota__c</fullName>
        <description>Run till Fill quota for the amount of records each user should be assigned to at a given time.</description>
        <inlineHelpText>Run till Fill quota for the amount of records each user should be assigned to at a given time.</inlineHelpText>
        <label>Record Assignment Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCaseAllocationUpdateTgr.cls
@isTest

public class TestCaseAllocationUpdateTgr {
    
    static testMethod void testCaseAllocationUpdateTgr(){
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        UserRole role = [SELECT Id, Name FROM UserRole WHERE Name = 'Customer Success Consultant'];
        RecordType  cRecType = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Case' AND Name = 'Customer Success Case - Surveys' LIMIT 1];
        Profile prof = [SELECT Id, Name FROM Profile WHERE Name IN ('Customer Success Consultant')];    
        
        System.runAs (thisUser) {
            //deactivate current users
            Test.startTest(); 
            /*List<User> currentUsers = [SELECT Id, FirstName, Current_Booking_Count__c, RTF_Booking_Quota__c 
                                       FROM User 
                                       WHERE UserRoleId =: role.Id
                                       AND ProfileId =: prof.Id 
                                       AND IsActive = TRUE];
            
            if(currentUsers.size() > 0 ) {
                for(User u : currentUsers) {
                    u.IsActive = false;
                }
            }
            
            update currentUsers;*/
            
            //create new users
            
            List<User> newUsers = new List<User>();
            for(Integer i = 0; i < 3; i++) {
                
                User u = new User();
                u.FirstName         = 'Elsa';
                u.LastName          = 'of Arendelle';
                u.Email             = 'elsa@disney.com';
                u.Alias             = 'elsa' + i;
                u.Username          = 'elsa' + i + '@disney.com';
                u.LocaleSidKey      = 'en_US';
                u.TimeZoneSidKey    = 'GMT';
                u.ProfileID         = prof.Id;
                u.UserRoleId        = role.Id;
                u.LanguageLocaleKey = 'en_US';
                u.EmailEncodingKey  = 'UTF-8';
                u.Current_Booking_Count__c = null;
                u.RTF_Booking_Quota__c = null;
                newUsers.add(u);    
            }
            
            insert newUsers;
            
            //create busy time log
            
            newUsers = [SELECT Id, Current_Booking_Count__c FROM User WHERE Id =: newUsers];
            
            Busy_Time_Log__c b = new Busy_Time_Log__c();
            
            b.Date__c = date.today();
            b.Start_Time__c = '00:00';
            b.End_Time__c = '23:45';
            b.User__c = newUsers[0].Id;
            b.Reason_for_Unavailability__c = 'test';
            
            insert b;
            
            
            
            //insert new cases
            
            List<Case> newCases = new List<Case>();
            for(Integer i=0; i < 100; i++) {
                Case c = new Case();
                c.Status = 'Pre-Check In';
                c.Status_Custom__c = 'TBD';
                c.RecordTypeId = cRecType.Id;
                newCases.add(c);
           }
            
            insert newCases;
            
            //verify that the cases are divided among each user
            List<User> usersWithCases = [SELECT Id, Current_Booking_Count__c FROM USER WHERE Id =: newUsers];
            
            //System.assertEquals(50, usersWithCases[1].Current_Booking_Count__c);
            //System.assertEquals(50, usersWithCases[2].Current_Booking_Count__c);
            
            
            //update stage to Check In and status to Email Complete of all new cases that belong to new users
            
            List<Case> updateCases = [SELECT Id, OwnerId from Case Where Id =: newCases And OwnerId =: newUsers];  
            
            for(Case c : updateCases) {
                
                c.Status = 'Check In';
                c.Status_Custom__c = 'Email Complete';
                
            }
            
            update updateCases;
            
            
            //verify that each user has 0 cases on their queue
            Test.stopTest(); 
            List<User> updatedUsrList = [SELECT Id, Current_Booking_Count__c FROM User WHERE Id =: newUsers];
            
            
           // for(User u : updatedUsrList) {
           //     System.assertEquals(0, updatedUsrList[1].Current_Booking_Count__c);
           // }
            
        }
        
    }
    
}