src/objects/Call_Log__c.object
<CustomObject>
    <fields>
        <fullName>Call_Date_Time__c</fullName>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Call_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Old_Stage__c</fullName>
        <label>Old Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_Status__c</fullName>
        <label>Old Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Log</label>
    <nameField>
        <displayFormat>CL{0000000000}</displayFormat>
        <label>Contact Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Status_Custom__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive to Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined to Engage/No Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, Awaiting Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, No Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Feedback to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestNewCaseCallLog.cls
@isTest

public class TestNewCaseCallLog {
    static testMethod void testNewCaseCallLog(){
         
        
        RecordType  cRecType = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Case' AND Name = 'Customer Success Case - Surveys' LIMIT 1];
        
        
        //insert new case
            
                Case c = new Case();
                c.Status = 'Check In';
                c.Status_Custom__c = 'Awaiting Call';
                c.RecordTypeId = cRecType.Id;
            
            insert c;
        
        //update case
        
        c.Status_Custom__c = 'Call Complete';
            
            update c;
        
        //verify that a call log is created
        
        List<Call_Log__c> callLogList = [SELECT Id, Call_Date_Time__c, Old_Stage__c, Stage__c, Old_Status__c, Status__c, Case__c
                                        FROM Call_Log__c WHERE Case__c =: c.Id];
        
        for(Call_Log__c cl : callLogList) {
            
             system.assertEquals('Check In', cl.Old_Stage__c);
             system.assertEquals('Check In', cl.Stage__c);
            system.assertEquals('Awaiting Call', cl.Old_Status__c);
            system.assertEquals('Call Complete', cl.Status__c);
        } 
            
    }
}