src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Check_In_Call_Date__c</fullName>
        <label>Check In Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Call_Date__c</fullName>
        <label>Customer Care Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Custom__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Status</controllingField>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive to Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Attempt 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remedial Action Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable To Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined to Engage/No Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, Awaiting Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Resolved, No Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Not Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Feedback to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy</label>
        <referenceTo>Vacancy__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <description>Vacancies are job placement adverts associated to one booking</description>
    <fields>
        <fullName>Customer_Care_Call_Date__c</fullName>
        <inlineHelpText>6 weeks after the ad has expired in the TES website. If the date falls on a Saturday or Sunday, the date would be on the Friday before those days.</inlineHelpText>
        <label>Customer Care Call Date</label>
        <type>Date</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelatedCasesController.cls
public class RelatedCasesController {


    public ApexPages.StandardController stdCon;
    
    public Case cs;
    public Id caseContactId { get; set; }
    public Id csId {get; set;}
    public List<Case> caseList = new List<Case>();
    
    public RelatedCasesController (ApexPages.StandardController stdCon) {
        this.cs = (case) stdCon.getRecord();
        this.stdCon = stdCon;
        
        caseContactId = this.cs.ContactId;
        csId = this.cs.Id;
       
    }
    
    
    public List<Case> getRelatedCases() {
        
        
        caseList = [SELECT Id, CaseNumber, Check_In_Call_Date__c, Customer_Care_Call_Date__c, 
                               OwnerId, AccountId, Vacancy__c, ContactId, Priority, Status, Status_Custom__c, 
                               Account.Name, Vacancy__r.Name, Contact.LastName, Contact.FirstName, 
                               Owner.FirstName, Owner.LastName
                              FROM Case
                              
                              WHERE ContactId =: caseContactId
                              AND ContactId !=: null
                              AND Id !=: csId
                              AND ((Check_In_Call_Date__c = LAST_WEEK OR Check_In_Call_Date__c = THIS_WEEK)
                              OR (Customer_Care_Call_Date__c = LAST_WEEK OR Customer_Care_Call_Date__c = THIS_WEEK))
                              ORDER BY Check_In_Call_Date__c DESC];
        
        
        return caseList;
        
    }
    
}