src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ABKHAZIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKROTIRI AND DHEKELIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALAND ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTARCTICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASHMORE AND CARTIER ISLANDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES, AUTONOMOUS REGION OF THE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Authority__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Local Authority</label>
        <referenceTo>Local_Authority__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SD_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SD Name</label>
        <referenceTo>Organisation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Account Co-Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Co-ordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessm. Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering Mgr/Superv.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair of Governors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Sci. Lab. Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dep Vice Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund Raising Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold / Silver Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Art</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>part_of_uk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part of UK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Local_Authority__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Country__c.part_of_uk__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>local_authorities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Local Authority</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Local Authorities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market_Share_Log__c.object
<CustomObject>
    <fields>
        <fullName>Current_Movement_Category__c</fullName>
        <label>Current Movement Category</label>
        <picklist>
            <picklistValues>
                <fullName>100% TES both years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100% TES to left TES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertised this year but not last</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertised this year but not last-new this week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertised TY only - Lost TES share WoW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Increased TES Share</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No advert YTD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-TES both years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reduced TES Share</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start share with others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped using TES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SD_Name__c</fullName>
        <label>SD Name</label>
        <referenceTo>Organisation__c</referenceTo>
        <relationshipLabel>Market Share Logs</relationshipLabel>
        <relationshipName>Market_Share_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Volumes_YTD__c</fullName>
        <label>Volumes YTD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Market Share Log</label>
    <nameField>
        <displayFormat>MS{0000000000}</displayFormat>
        <label>Market Share Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Share Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>organisations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Movement_Category__c</fullName>
        <label>Current Movement Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volumes_YTD__c</fullName>
        <label>Volumes YTD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>local_authority__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Local Authority</label>
        <referenceTo>Local_Authority__c</referenceTo>
        <relationshipLabel>Organisations</relationshipLabel>
        <relationshipName>organisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <recordTypes>
        <fullName>school</fullName>
        <active>true</active>
        <label>School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateAmbVisitDate.cls
@isTest
public class TestUpdateAmbVisitDate {
    
    static testmethod void TestUpdateAmbVisitDate(){
        
        test.startTest();
        
         //insert country
        Country__c country = new Country__c ();
        country.Name = 'TEST';
        country.title__c = 'TEST';
        country.part_of_uk__c = TRUE;
        
        insert country;
        
        //insert local authority
        Local_Authority__c localAuthority = new Local_Authority__c ();
        localAuthority.Name = 'Test Local Authority';
        localAuthority.Region__c = 'Test Region';
        localAuthority.Country__c = country.Id;
        
        insert localAuthority;
        
        //insert organisation
        Organisation__c org = new Organisation__c();
        org.Name = 'Test School';
        org.Address_1__c = 'Test Address 1';
        org.County__c = 'Test County';
        org.Postcode__c = '123321';
        org.Country__c = country.Id;
        org.local_authority__c = localAuthority.Id;
        
        insert org;
        
        //insert market share log
        Market_Share_Log__c mktShare = new Market_Share_Log__c();
        mktShare.Current_Movement_Category__c = '100% TES to left TES';
        mktShare.Volumes_YTD__c = 12;
        mktShare.SD_Name__c = org.Id;
        
        insert mktShare;
        
        //select the case that was inserted when market share log is inserted
        Case newMarketShareCase = [SELECT Id, SD_Name__c, RecordTypeId, Origin, Status, Status_Custom__c, Priority FROM Case WHERE SD_Name__c =: org.Id];
   		
        RecordType ambassadorVisitEventRT = [SELECT Id FROM RecordType WHERE sObjectType = 'Event' AND Name = 'Ambassador Visit'];
        
        //insert an event against the market share case
        Event ambassadorVisit = new Event();
        ambassadorVisit.ActivityDate = date.newInstance(2015, 09, 13);
        ambassadorVisit.Location = 'test location';
        ambassadorVisit.RecordTypeId = ambassadorVisitEventRT.Id;
        ambassadorVisit.Subject = 'test';
        ambassadorVisit.WhatId = newMarketShareCase.Id;
        ambassadorVisit.DurationInMinutes = 60;
        ambassadorVisit.StartDateTime = datetime.newInstance(2015, 09, 13, 7, 8, 16);
        ambassadorVisit.EndDateTime = datetime.newInstance(2015, 09, 13, 8, 8, 16);
        
        insert ambassadorVisit;
        
        test.stopTest();
        
        //verify that the case ambassador status is updated
        Case updatedCase = [SELECT Id, Status, Status_Custom__c FROM Case WHERE Id =: newMarketShareCase.Id];
        
        system.assertEquals(updatedCase.Status, 'Ambassador Contact');
        system.assertEquals(updatedCase.Status_Custom__c, 'Awaiting Visit');
        
        //verify that the org scheduled visit date is updated
        Organisation__c updatedorg = [SELECT Id, Visit_Start_Date_Time__c, Visit_End_Date_Time__c FROM Organisation__c WHERE Id =: org.Id];
        
        system.assertEquals(updatedorg.Visit_Start_Date_Time__c, datetime.newInstance(2015, 09, 13, 7, 8, 16));
        system.assertEquals(updatedorg.Visit_End_Date_Time__c, datetime.newInstance(2015, 09, 13, 8, 8, 16));
    }

}