src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Main_Reason_for_Complaint__c</fullName>
        <label>Main Reason for Complaint</label>
        <picklist>
            <picklistValues>
                <fullName>Advert Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advert Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booking Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communication Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount/Upgrade Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Advert/Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice/Billing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing/Rating Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Related to Customer Success Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reported_By_Team__c</fullName>
        <label>Reported By (Team)</label>
        <picklist>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell P&amp;O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reported_By__c</fullName>
        <label>Reported By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Complaints</fullName>
        <active>true</active>
        <businessProcess>Complaints Process</businessProcess>
        <description>Case record type used to record any complaints from customers</description>
        <label>Complaints</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Remedial_Action__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <label>Approver Name</label>
        <picklist>
            <picklistValues>
                <fullName>Julia Rontree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gavin Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gareth Thyer-Jones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michelle Reid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Becky Simpson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Remedial Actions</relationshipLabel>
        <relationshipName>Remedial_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Very High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Very Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_Credit__c</fullName>
        <label>Reason for Credit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Given</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer Given</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Remedial Action</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Remedial Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remedial Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QmsFormController.cls
public class QmsFormController {
    
    public Case cs {get; set;}
    public Remedial_Action__c ra {get; set;}
    
    RecordType complaintsRT = [SELECT Id, Name 
                               FROM RecordType 
                               WHERE sObjectType = 'Case' 
                               AND Name = 'Complaints'];
    
    public ApexPages.StandardSetController stdSetController;
    public QmsFormController(ApexPages.StandardSetController stdSetController) {
        cs = new Case(origin = 'QMS', 
                      Reported_By_Team__c = 'Finance', 
                      Reported_By__c = 'Julia Rontree',
                      Status = 'Closed - Resolved', 
                      Main_Reason_for_Complaint__c = 'Invoice/Billing Issue', 
                      RecordTypeId = complaintsRT.Id
                     );
        
        ra = new Remedial_Action__c(Status__c = 'Credit Given', Approver_Name__c = 'Julia Rontree', Priority__c = '3 - Medium');
        
        this.stdSetController = stdSetController; 
    }
    
     public PageReference saveQMSForm() {
       Savepoint sp = Database.setSavepoint(); 
        
       try { 
           
       cs.RecordTypeId = complaintsRT.Id;    
      
       insert cs;
       
       ra.Case__c = cs.Id;
       ra.Reason_for_Credit__c = cs.Description;
       
       insert ra;
       
       PageReference pg = new PageReference('/' + cs.Id);
       return pg;      
           
       } catch(DmlException e) {
           ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getdmlMessage(0));
           ApexPages.addMessage(msg);
           Database.rollback(sp); 
           cs = cs.clone(false);
            return null;
        }
        
        return null;  
        
    }  

}