src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generated Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SD_ID__c</fullName>
        <label>SD ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School_Id__c</fullName>
        <formula>IF(ISNULL(SD_ID__c),
Account.School_ID__c,
23)</formula>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>CALLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRIME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Account Co-Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Co-ordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessm. Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering Mgr/Superv.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair of Governors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Sci. Lab. Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dep Vice Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund Raising Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold / Silver Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Art</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Headteacher</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>organisations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Id__c</fullName>
        <externalId>true</externalId>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <recordTypes>
        <fullName>school</fullName>
        <active>true</active>
        <label>School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSD3ContactImport.cls
@isTest
private class TestSD3ContactImport {
	
	@isTest static void test_method_one() 
	{
		Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Contact; 
		Map<String,Schema.RecordTypeInfo> contactRedcordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
		Id crtId = contactRedcordTypeInfo.get('SD3 School contact').getRecordTypeId();

		Country__c con = new Country__c();
		con.Name = 'ESP';
		con.title__c = 'Spain';
		insert con;

		Organisation__c o = new Organisation__c();
		o.Name = 'test';
		o.Address_1__c = 'test';
		o.Postcode__c = 'W2 4RL';
		o.Country__c = con.Id;
		o.County__c = 'Test';
		o.School_Id__c = 12345;
		insert o;

		List<Contact> contacts = new List<Contact>();

		for(Integer i=0;i<200;i++)
		{
			Contact c = new Contact();
			c.RecordTypeId = crtId;
			c.FirstName = 'test' + i;
			c.LastName = 'test' + i;
			c.Source__c = 'MSL' + i;
			c.Gen__c = true;
			c.Title__c = 'Headteacher' + i;
			c.Email = 'test@test.com' + i;
			c.SD_ID__c = o.School_Id__c;
			contacts.add(c);
		}
		
		Test.startTest();
		insert contacts;
		Test.stopTest();
	}
	
}