src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Gen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generated Email?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>CALLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WEB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRIME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Account Co-Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Co-ordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessm. Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bursar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catering Mgr/Superv.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chair of Governors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Sci. Lab. Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deputy Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dep Vice Chancellor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Director of Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund Raising Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold / Silver Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of Art</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head of assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation__c.object
<CustomObject>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <recordTypes>
        <fullName>school</fullName>
        <active>true</active>
        <label>School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/School_contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>School_contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Organisation__c</referenceTo>
        <relationshipName>School_contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>School Contact</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>School Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>School Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SchoolContactCollection.cls
/*
	CDA
*/
public with sharing class SchoolContactCollection
{
	public String orgName	{get; set;}
	public List<ContactBean> contacts {get; set;}
	private Id orgId;

	public SchoolContactCollection()
	{
		Id orgId = ApexPages.currentPage().getParameters().get('Id');
		String name = ApexPages.currentPage().getParameters().get('name');

		if (orgId != null)
		{
			List<School_contact__c> sclist = [SELECT Id, Name, Contact__r.Salutation, Contact__r.Title__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Source__c, Contact__r.Gen__c, Contact__r.Email, Contact__r.Comments__c, Contact__c, Organisation__r.Name  FROM School_contact__c WHERE Organisation__c = :orgId];
			this.orgName = name;
			this.orgId = orgId;
			this.getAllContacts(sclist);
			System.debug('sclist: ' + sclist);
		}
	}

	private void getAllContacts(List<School_contact__c> sclist)
	{
		List<ContactBean> contactlist = new List<ContactBean>();
		for (School_contact__c sc : sclist)
		{
			ContactBean c = getContactBeanFromSchoolContact(sc);
			contactlist.add(c);
		}

		if (contactlist.size() > 0)
			this.contacts = contactlist;
		else
			this.addContact();
	}

	private ContactBean getContactBeanFromSchoolContact(School_contact__c sc)
	{
		ContactBean cb = new ContactBean();
		cb.id = sc.Contact__c;
		cb.salutation = sc.Contact__r.Salutation;
		cb.firstName = sc.Contact__r.FirstName;
		cb.lastName = sc.Contact__r.LastName;
		cb.source = sc.Contact__r.Source__c;
		cb.title = sc.Contact__r.Title__c;
		cb.gen = sc.Contact__r.Gen__c;
		cb.email = sc.Contact__r.Email;
		cb.comments = sc.Contact__r.Comments__c;
		cb.sc_name = sc.Name;

		return cb;
	}

	private Contact getContactFromContactBean(ContactBean cb)
	{
		Contact c = new Contact();
		c.Id = cb.id;
		c.Salutation = cb.salutation;
		c.FirstName = cb.firstName;
		c.LastName = cb.lastName;
		c.Source__c = cb.source;
		c.Title__c = cb.title;
		c.Gen__c = cb.gen ;
		c.Email = cb.email;
		c.Comments__c = cb.comments;

		return c;
	}

	public List<SelectOption> getSourceValues()
	{
		List<SelectOption> options = new List<SelectOption>();

		Schema.DescribeFieldResult fieldResult = Contact.Source__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

		for (Schema.PicklistEntry f : ple)
		{
			options.add(new SelectOption(f.getLabel(), f.getValue()));
		}

		return options;
	}

	public List<SelectOption> getSalutationValues()
	{
		List<SelectOption> options = new List<SelectOption>();

		Schema.DescribeFieldResult fieldResult = Contact.Salutation.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

		for (Schema.PicklistEntry f : ple)
		{
			options.add(new SelectOption(f.getLabel(), f.getValue()));
		}

		return options;
	}

	public List<SelectOption> getTitleValues()
	{
		List<SelectOption> options = new List<SelectOption>();

		Schema.DescribeFieldResult fieldResult = Contact.Title__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

		for (Schema.PicklistEntry f : ple)
		{
			options.add(new SelectOption(f.getLabel(), f.getValue()));
		}

		return options;
	}

	public void addContact()
	{
		if (contacts == null)
			contacts = new List<ContactBean>();
		ContactBean c = new ContactBean();
		c.sc_name = 'New';
		contacts.add(c);
	}

	public PageReference savechanges()
	{
		List<Contact> contactsToUpdate = new List<Contact>();
		List<Contact> contactsToInsert = new List<Contact>();
		for (ContactBean cb : contacts)
		{
			Contact c = this.getContactFromContactBean(cb);
			if (c.Id == null)
			{
				c.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('SD3 School contact').getRecordTypeId();
				contactsToInsert.add(c);
			}
			else
			{
				contactsToUpdate.add(c);
			}
		}

		update contactsToUpdate;

		if (contactsToInsert.size() > 0)
		{
			insert contactsToInsert;
			List<School_contact__c> scToInsert = new List<School_contact__c>();
			for (Contact c : contactsToInsert)
			{
				School_contact__c sc = new School_contact__c();
				sc.Contact__c = c.Id;
				sc.Organisation__c = orgId;
				scToInsert.add(sc);
			}

			insert scToInsert;
		}

		return new PageReference('/' + orgId);
	}


	public class ContactBean
	{
		public Id id {get; set;}
		public String salutation {get; set;}
		public String lastName {get; set;}
		public String firstName {get; set;}
		public String source {get; set;}
		public String comments {get; set;}
		public String title {get; set;}
		public Boolean gen {get; set;}
		public String email {get; set;}
		public String sc_name {get; set;}
	}

}