src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>organisations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <recordTypes>
        <fullName>school</fullName>
        <active>true</active>
        <label>School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSchoolMapExtension.cls
@isTest
public class TestSchoolMapExtension {
    
    public static TestMethod void TestSchoolMapExtension(){
        
        //insert country
        Country__c cy = new Country__c ();
        cy.Name = 'TEST';
        cy.title__c = 'TEST';
        
        insert cy;
        
        //insert organisation
        Organisation__c org = new Organisation__c();
        org.Name = 'Test School';
        org.Address_1__c = 'Test Address 1';
        org.County__c = 'Test County';
        org.Postcode__c = '123321';
        org.Country__c = cy.Id;
        
        insert org;
        
        Test.startTest();
        PageReference pageRef = Page.SchoolMapPage;
        Test.setCurrentPage(pageRef);
        
         // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', org.Id);
        SchoolMapExtension ext = new SchoolMapExtension(new ApexPages.StandardController(org) );
	   ext.phasesFilter.add('secondary');
        
        List<String> phaseList = ext.phasesFilter;
        phaseList.add('Primary');
        phaseList.add('Secondary');
        
        ext.filterKeys.put('Phase', phaseList);
        
        String phases = ext.phases;
        
        List<String> fundingGroupList = ext.fundingGroupFilter;
        fundingGroupList.add('State');
        fundingGroupList.add('Independent');
        
        ext.filterKeys.put('Funding Group', fundingGroupList);
        
        String fundingGroups = ext.fundingGroups;
        
        ext.createfilterMap();
        
        SchoolMapExtension ext2 = new SchoolMapExtension();
        
        SchoolMapExtension ext3 = new SchoolMapExtension(new ApexPages.StandardController(org) );
        
        List<String> emptyPhasesList = null;
        emptyPhasesList = ext3.phasesFilter;
        ext3.filterKeys.put('Phase', emptyPhasesList);
        String emptyphases = ext3.phases;
        
        List<String> emptyFundingGroupsList = null;
        emptyFundingGroupsList = ext3.fundingGroupFilter;
        ext3.filterKeys.put('Funding Group', emptyFundingGroupsList);
        String emptyfundinggroup = ext3.fundingGroups;
        
        test.stopTest();
        
    }

}