src/objects/Folder__c.object
<CustomObject>
    <description>Contains all the inbox and subfolders from TES Outlook.</description>
    <fields>
        <fullName>Parent_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mailbox</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>SubFolders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubFolderListController.cls
public class SubFolderListController {
    
    public Id elementId {get; set;}
    
    public SubFolderListController() {
     //   System.debug('HERREEE!!!!!!! -->' + elementId);
    //    subFolderList = [SELECT Id, Name FROM Folder__c WHERE parent_folder__c = :elementId];
      //  System.debug('Results!!!!!!! -->' + subFolderList);

    }
    
    public List<Folder__c> getSubFolderList() {
         System.debug('HERREEE!!!!!!! -->' + elementId);
        
        return [SELECT Id, Name FROM Folder__c WHERE parent_folder__c = :elementId ORDER BY Name ASC];
    }

}