src/objects/Folder__c.object
<CustomObject>
    <description>Contains all the inbox and subfolders from TES Outlook.</description>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ad_Number__c</fullName>
        <description>Booking Reference Number</description>
        <externalId>true</externalId>
        <label>Ad Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <formula>IF(ISPICKVAL(Email_Status__c, &quot;Unread&quot;), IMAGE(&quot;/resource/1417620259000/Flag7_TBD&quot;, &quot;7 - TBD&quot;, 18, 18), 

IF(ISPICKVAL(Email_Status__c, &quot;Account on Stop&quot;), IMAGE(&quot;/resource/1417620273000/Flag8_OnStop&quot;, &quot;8 - Account on Stop&quot;, 18, 18), 

IF(NOT(ISBLANK(Ad_Number__c)), IMAGE(&quot;/resource/1417620289000/Flag9_Booked&quot;, &quot;9 - Booked&quot;, 18, 18), 

IF(Elapsed_Time_No_Bus_Hrs__c &gt; 480, IMAGE(&quot;/resource/1417619901000/Flag1_8Hrs&quot;, &quot;1 - Very High (+8 Hrs)&quot;, 18, 18),

IF(AND(Elapsed_Time_No_Bus_Hrs__c &gt; 240, Elapsed_Time_No_Bus_Hrs__c &lt;= 480), IMAGE(&quot;/resource/1417620124000/Flag2_4Hrs&quot;, &quot;2 - Very High (+4 Hrs)&quot;, 18, 18),

IF(AND(Elapsed_Time_No_Bus_Hrs__c &gt; 120, Elapsed_Time_No_Bus_Hrs__c &lt;= 240), IMAGE(&quot;/resource/1417620189000/Flag3_2Hrs&quot;, &quot;3 - High (+2 Hrs)&quot;, 18, 18),

IF(OR(CONTAINS(Folder__r.Name, &quot;Gold&quot;), 
CONTAINS(Folder__r.Name, &quot;Silver&quot;), 
CONTAINS(Folder__r.Name, &quot;Leadership/FE&quot;) 
), 
   IMAGE(&quot;/resource/1417620208000/Flag4_High&quot;, &quot;4 - High&quot;, 18, 18),

IF(OR(ISPICKVAL(Online_Job_Type__c, &quot;Gold&quot;), 
ISPICKVAL(Online_Job_Type__c, &quot;Silver&quot;) 
), 
IMAGE(&quot;/resource/1417620208000/Flag4_High&quot;, &quot;4 - High&quot;, 18, 18),

IF(AND(Elapsed_Time_No_Bus_Hrs__c &lt;= 120, Elapsed_Time_No_Bus_Hrs__c &gt; 60), IMAGE(&quot;/resource/1417620223000/Flag5_Medium&quot;, &quot;5 - Medium (1-2 Hrs)&quot;, 18, 18),

IF(Elapsed_Time_No_Bus_Hrs__c &lt;=60, IMAGE(&quot;/resource/1417620239000/Flag6_Low&quot;, &quot;6 - Low (&lt;1 Hr)&quot;, 18, 18), 

IMAGE(&quot;/resource/1417620259000/Flag7_TBD&quot;, &quot;7 - TBD&quot;, 18, 18)))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Flag color corresponding to each Priority.</inlineHelpText>
        <label>Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailbox__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mailbox</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>ParentBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BookingsSales</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CCEmailArchiveService.cls
global with sharing class CCEmailArchiveService {
	/*public static String listEndpoint = 'https://cloudreach-connect-shared.herokuapp.com/ccsvc/tes/email/list';
	public static String authKey = '2203ef9c-8c3f-44dd-bfcc-4ba67ae64406';
	
	public String lastJsonResponse { get; set; }
	
	public HTTPResponse sendCommand(String method,String endpoint,Map<String,String> paramList) {
		HTTPRequest request = new HTTPRequest();
		request.setEndpoint(endpoint);
		request.setHeader('AuthKey', authKey);
		request.setHeader('referer', System.URL.getSalesforceBaseUrl().toExternalForm());
		request.setMethod(method);
		request.setHeader('Content-Type','application/x-www-form-urlencoded');
		
		String reqBody = null;
		for(String paramKey : paramList.keySet()) {
			if(reqBody != null) {
				reqBody += '&';
			}
			String encodedParam = EncodingUtil.urlEncode(paramKey, 'UTF-8')+'='+EncodingUtil.urlEncode(paramList.get(paramKey),'UTF-8');
			reqBody = (reqBody == null ?  encodedParam : reqBody + encodedParam);
		}
		//reqBody = (reqBody == null ? 'key='+EncodingUtil.urlEncode(authKey,'UTF-8') : reqBody + '&key='+EncodingUtil.urlEncode(authKey,'UTF-8'));
		if(method == 'GET') {
			request.setEndpoint(endpoint+'?'+reqBody);
		} else {
			request.setHeader('Content-Length',String.valueOf(reqBody.length()));
			request.setBody(reqBody);
		}
		
		Http http = new Http();
		return http.send(request);
	}
	
	public TESMessage getFirstMessage(Id opportunityId) {
		Map<String,String> paramMap = new Map<String,String>();
		paramMap.put('oppId',opportunityId);
		paramMap.put('pos','FIRST');
		
		String jsonBody = sendCommand('GET',listEndpoint,paramMap).getBody();
		if(jsonBody != null && jsonBody.length() != 0) {
			return (TESMessage)JSON.deserialize(jsonBody,TESMessage.class);
		}
		
		return null;
	}
	
	public void moveMessage(String messageId,Id newOpportunityId) {
		Map<String,String> paramMap = new Map<String,String>();
		paramMap.put('oppId',newOpportunityId);
		paramMap.put('act','CHANGE_OPPORTUNITY');
		paramMap.put('msgId',messageId);
		
		String jsonBody = sendCommand('POST',listEndpoint,paramMap).getBody();
	}
	
	public class MessageList {
		public List<TESMessage> messages { get; set; }
	}
	
	public List<TESMessage> listMesssages(Id opportunityId) {
		Map<String,String> paramMap = new Map<String,String>();
		paramMap.put('oppId',opportunityId);
		
		String jsonList = sendCommand('GET',listEndpoint,paramMap).getBody();
		if(jsonList != null && jsonList.length() != 0) {
			String jsonBody = '{ "messages" : '+jsonList+'}';
			lastJsonResponse = jsonBody;
			MessageList msgList = (MessageList)JSON.deserialize(jsonBody,MessageList.class);
			
			return msgList.messages;
		}
		
		return new List<TESMessage>();
	}
	
	global class EmailAttachment {
		public Integer id = 0;
		public Integer inbox_id = 0;
		public String filename {set; get; }
		public String contentType = null;
		public Long file_length = 0;
		public String url {set; get; }
		public String opportunity_id = null;
	}
	
	public class EmailAttachmentList {
		public Integer currentPage { get; set; }
		public Integer totalPages { get; set; }
		public List<EmailAttachment> results { get; set; }
	}
	
	public class OpportunityResult {
		public Opportunity opportunity = null;
		public EmailAttachment attachment = null;
	}
	
	global class OpportunityListResult {
		public Integer numPages = 0;
		public Integer currentPage = 0;
		public Integer nextPage = 0;
		public Integer prevPage = 0;
		public List<OpportunityResult> results = null;
	}
	
	public OpportunityListResult searchAttachments(String searchText,Integer page) {
		OpportunityListResult result = new OpportunityListResult();
		
		//we need to execute the search for attachments remotely on the heroku server.
		Map<String,String> paramMap = new Map<String,String>();
		paramMap.put('act','ATTACHMENT_SEARCH');
		paramMap.put('pg',String.valueOf(page));
		paramMap.put('src',searchText);
		
		Map<Id,OpportunityResult> resultMap = new Map<Id,OpportunityResult>();
		String jsonList = sendCommand('POST',listEndpoint,paramMap).getBody();
		if(jsonList != null && jsonList.length() != 0) {
			EmailAttachmentList srcResult = (EmailAttachmentList)JSON.deserialize(jsonList,EmailAttachmentList.class);
			result.numPages = srcResult.totalPages;
			result.currentPage = srcResult.currentPage;
			if(page > 1) {
				result.prevPage = page - 1;
			} else {
				result.prevPage = page;
			}
			if(page < result.numPages) {
				result.nextPage = page + 1;
			} else {
				result.nextPage = page;
			}
			result.results = new List<OpportunityResult>();
			for(EmailAttachment attachment : srcResult.results) {
				OpportunityResult rowResult = new OpportunityResult();
				rowResult.attachment = attachment;
				result.results.add(rowResult);
				resultMap.put(attachment.opportunity_id,rowResult);
			}
		}
		Opportunity[] oppList = [Select Id,Name,CreatedDate,Account.Name,Ad_Number__c,Flag__c,Mailbox__r.Id,Mailbox__r.Name,
															Folder__r.Id,Folder__r.Name,Sales_Rep__r.Id,Sales_Rep__r.Name,Owner.Id,Owner.Name from Opportunity
															where Id in :resultMap.keySet()];
		for(Opportunity opp : oppList) {
			OpportunityResult rowResult = resultMap.get(opp.Id);
			rowResult.opportunity = opp;
		}
		//now make sure there are only results which are connected to an opportunity which exists.
		List<OpportunityResult> actualResults = new List<OpportunityResult>();
		for(OpportunityResult oppResult : result.results) {
			if(oppResult.opportunity != null) {
				actualResults.add(oppResult);
			}
		}
		result.results = actualResults;
		
		return result;
	}
	
	public List<EmailAttachment> getMessageAttachments(String messageId) {
		Map<String,String> paramMap = new Map<String,String>();
		paramMap.put('msgId',messageId);
		
		Map<Id,OpportunityResult> resultMap = new Map<Id,OpportunityResult>();
		String jsonList = sendCommand('GET',listEndpoint,paramMap).getBody();
		if(jsonList != null && jsonList.length() != 0) {
			EmailAttachmentList srcResult = (EmailAttachmentList)JSON.deserialize('{ "currentPage" : 1, "totalPages" : 0, "results" : '+jsonList+' }',EmailAttachmentList.class);
			return srcResult.results;
		}
		
		return new List<EmailAttachment>();
	}*/
}