src/objects/Folder__c.object
<CustomObject>
    <description>Contains all the inbox and subfolders from TES Outlook.</description>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <recordTypes>
        <fullName>Folder</fullName>
        <active>true</active>
        <description>Sub folders in a mailbox.</description>
        <label>Folder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mailbox</fullName>
        <active>true</active>
        <description>Mailbox folder that receives all emails.</description>
        <label>Mailbox</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Folder_Picklist__c</fullName>
        <label>Folder</label>
        <picklist>
            <controllingField>Mailbox_Picklist__c</controllingField>
            <picklistValues>
                <fullName>1. Gold - Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1. Gold - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1. Leadership/FE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1. Leadership/FE - Space Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Leadership/FE - Mac Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Mac Ads A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Silver - Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Silver - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Bronze and Starter - Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Bronze and Starter - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Mac Ads B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Space Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Account on Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Mac Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Mac Logos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Account on Stop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Amendments - Leadership/FE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Amendments - Leadership/FE - Mac Ads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Manchester Primary +</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Amendments - Mac Ads - Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Amendments - Mac Ads - Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Awaiting PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Sent to Artwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7. Space Bookings - DONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Future Adverts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8. Mac Ads - DONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Amendments - DONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9. Downsells</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailbox_Picklist__c</fullName>
        <label>Mailbox</label>
        <picklist>
            <picklistValues>
                <fullName>Agency - Online Only</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Agency - Print Ads</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Agency Web Amends</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Direct - Online Only</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Direct - Recruitment</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Web Amends</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Hirewire TES</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>Online School Groups</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Plus</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
                <color>#F96FB7</color>
            </picklistValues>
            <picklistValues>
                <fullName>TES Australia</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>TES International</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>TES Internet Jobs</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>TES Support</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>TES Wales</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>THE Artwork</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>THE Recruitment</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>THE Support</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>THE Web Amends</fullName>
                <color>#A845DC</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailbox__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mailbox</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>ParentBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUpdateFolderTgr.cls
@isTest
public class TestUpdateFolderTgr {
    static testMethod void testUpdateFolder(){
        
    // Set up the Folder record.
    folder__c mailbox = new folder__c(Name= 'Agency - Online Only');
    insert mailbox;
      
    folder__c folder = new folder__c(Name= '1. Gold Agency');
    insert folder;  
    
    RecordType bookingRT = [SELECT Id FROM RecordType WHERE sObjectType = 'Opportunity' AND Name = 'SFDC Booking'];
        
    // Insert the Opportunity record.
    Opportunity opp = new Opportunity(Name='Test Booking', 
                                      StageName='TBD',
                                      CloseDate=Date.today(),
                                      Mailbox_Picklist__c = 'Agency - Online Only', 
                                      Folder_Picklist__c = '1. Gold Agency',
                                      RecordTypeId = bookingRT.Id );
    
    //Trigger to update Mailbox and Folder lookups should execute.
    insert opp;
        
    //Verify that the Mailbox and Folder lookup fields are updated with the IDs of the new folders added that 
    //has the same name as the picklist values selected.
    opp = [SELECT Mailbox_Picklist__c, Folder_Picklist__c, Mailbox__c, Folder__c 
           FROM Opportunity 
           WHERE Id = :opp.Id];
   
    System.assertEquals(mailbox.Id, opp.Mailbox__c);
    System.assertEquals(folder.Id, opp.Folder__c);  
    
    //Verify the trigger works on update.    
    opp.Mailbox_Picklist__c=null;
    opp.Folder_Picklist__c=null;
    update opp;
        
    opp = [SELECT Mailbox_Picklist__c, Folder_Picklist__c, Mailbox__c, Folder__c 
           FROM Opportunity 
           WHERE Id = :opp.Id];
   
    System.assertEquals(null, opp.Mailbox__c);
    System.assertEquals(null, opp.Folder__c);    
        
    }
}