src/objects/Organisation__c.object
<CustomObject>
    <fields>
        <fullName>Complete_Address__c</fullName>
        <formula>IF(NOT(ISBLANK(Address_1__c)), Address_1__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK(Address_2__c)), BR() &amp; Address_2__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK(Address_3__c)), BR() &amp; Address_3__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK(Town__c)), BR() &amp; Town__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK( local_authority__r.Name  )), BR() &amp; local_authority__r.Name, &quot;&quot;)
&amp; IF(NOT(ISBLANK(County__c)), BR() &amp; County__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK(Postcode__c)), BR() &amp; Postcode__c, &quot;&quot;)
&amp; IF(NOT(ISBLANK(Country__r.title__c)), BR() &amp; Country__r.title__c, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Complete Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <formula>Country__r.title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Movement_Category__c</fullName>
        <label>Current Movement Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Since_Last_Visit__c</fullName>
        <description>The most current visit status for this school.</description>
        <formula>IF(NOT(ISBLANK(Date_Visited_by_Ambassador__c)),

&quot;Last visited &quot; &amp; TEXT(today() - Date_Visited_by_Ambassador__c) &amp; &quot; days ago&quot;,

IF(AND(
       NOT(ISBLANK( Visit_Start_Date_Time__c )),
       NOT(ISBLANK( Visit_End_Date_Time__c ))
       ),

&quot;Visit Scheduled on &quot; &amp; LEFT(TEXT(Visit_Start_Date_Time__c), 10) &amp; &apos; (&apos; &amp; Scheduled_Date_Start_Time__c &amp; &apos; to &apos; &amp; Scheduled_Date_End_Time__c &amp; &apos;)&apos;,

&quot;Not yet visited&quot;))</formula>
        <inlineHelpText>The most current visit status for this school.</inlineHelpText>
        <label>Visit Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Group__c</fullName>
        <label>Funding Group</label>
        <picklist>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <formula>lat_long__Latitude__s</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <formula>lat_long__Longitude__s</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Early years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sixth Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further 16+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Further (Other)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Phase</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Phase_and_Funding_Group__c</fullName>
        <formula>IF( 
NOT(ISBLANK(TEXT(Funding_Group__c))), TEXT(Funding_Group__c) &amp; &quot; /&quot;, &quot;&quot;)
&amp;
IF(
INCLUDES(Phase__c, &quot;Early years&quot;),
&quot; Early years /&quot;,&quot;&quot;)
&amp;

 IF( 
INCLUDES(Phase__c, &quot;Primary&quot;),
&quot; Primary /&quot;, &quot;&quot;)
 &amp;

IF( 
INCLUDES(Phase__c, &quot;Middle&quot;),
&quot; Middle /&quot;, &quot;&quot;)
 &amp;

 IF( 
INCLUDES(Phase__c, &quot;Secondary&quot;),
&quot; Secondary /&quot;, &quot;&quot;)
 &amp;

 IF( 
INCLUDES(Phase__c, &quot;Sixth Form&quot;),
&quot; Sixth Form /&quot;, &quot;&quot;)
 &amp;

 IF( 
INCLUDES(Phase__c, &quot;Further 16+&quot;),
&quot; Further 16+ /&quot;, &quot;&quot;)
 &amp;

 IF( 
INCLUDES(Phase__c, &quot;Further (Other)&quot;),
&quot; Further (Other) /&quot;, &quot;&quot;)
 &amp;

 IF( 
INCLUDES(Phase__c, &quot;Higher&quot;),
&quot; Higher /&quot;, &quot;&quot;)
 &amp;
 
 IF( 
INCLUDES(Phase__c, &quot;Multi-Phase&quot;),
&quot; Multi-Phase /&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phase and Funding Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Scheduled_to_Visit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scheduled to Visit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Id__c</fullName>
        <externalId>true</externalId>
        <label>School Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>School_Type__c</fullName>
        <label>School Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mainstream School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Provision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Maintained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pupil Referral Unit(PRU)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secure Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed to open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed to close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visited_by_Ambassador__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visited by Ambassador</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>lat_long__c</fullName>
        <label>Lat/Long</label>
        <scale>14</scale>
        <type>Location</type>
    </fields>
    <label>Organisation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisations</pluralLabel>
    <recordTypes>
        <fullName>school</fullName>
        <active>true</active>
        <label>School</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SchoolMapExtension.cls
public class SchoolMapExtension {
    
    public ApexPages.StandardController stdController;
    public Organisation__c org {get; set;}
    public Double orgLat {get; set;}
    public Double orgLong {get; set;}
    public Double distance {get; set;}
    
    public List<String> phasesFilter {get; set;}
    public List<String> fundingGroupFilter {get; set;}
    public List<String> fundingTypeFilter {get; set;}
    
    public String currentOrgId {get; set;}
    
    public String phases {get{
        
        if(filterKeys.get('Phase').size() > 0) {
        
            phases = String.join(filterKeys.get('Phase'), '\',\'');
            return phases;
        }
        
        else {
            
            phases = null;
            
            return phases;
        }
    }
        set;}
     
    public String fundingGroups {get{
        
        if(filterKeys.get('Funding Group').size() > 0) {
        
        String fundingGroups = String.join(filterKeys.get('Funding Group'), '\',\'');
        return fundingGroups;
        }
        
        else{
            fundingGroups = null;
            
            return fundingGroups;
            
        }
    }
        set;}
    
    public List<Organisation__c> listofSchools {get 
    
    {
        List<Organisation__c> filteredList = new List<Organisation__c>();
        List<Organisation__c> allSchools = new List<Organisation__c>();
          
        if(org == null) {
          allSchools = [SELECT Id,School_Id__c, Days_Since_Last_Visit__c, Scheduled_to_Visit__c, Visited_by_Ambassador__c, Phase_and_Funding_Group__c, Funding_Group__c, Name, lat_long__c,lat_long__Latitude__s, lat_long__Longitude__s, Complete_Address__c, Phase__c, Phone_Number__c, Current_Movement_Category__c FROM Organisation__c WHERE Country_Text__c = 'England' AND (Status__c = 'Open' OR Status__c = 'Proposed to open') AND School_Type__c = 'Mainstream School' AND (Phase__c includes ('Secondary') OR Phase__c = 'Multi-Phase')];
      	  return allSchools;
        }
        
        else if(phases == null && fundingGroups == null) {
   
        return listofSchools;
            
        }
        
        else{
        
        filteredList = Database.query('SELECT Id,School_Id__c, Scheduled_to_Visit__c, Days_Since_Last_Visit__c, Visited_by_Ambassador__c, Phase_and_Funding_Group__c, Funding_Group__c, Name, lat_long__c,lat_long__Latitude__s, lat_long__Longitude__s, Complete_Address__c, Phase__c, Phone_Number__c, Current_Movement_Category__c FROM Organisation__c WHERE Id =: currentOrgId OR ((Funding_Group__c IN (\''+fundingGroups+'\') OR Phase__c INCLUDES (\''+phases+'\')) AND (Status__c = \'Open\' OR Status__c = \'Proposed to open\') AND Distance(lat_long__c, GEOLOCATION('+orgLat+', '+orgLong+'),\'km\') < '+distance+')'); 
        return filteredList;
            
        }
      
    } set;}
    
    
    public Map<String, List<SelectOption>> filterMap {get; set;}
    public Map<String, List<string>> filterKeys {get; set;}
    
    public SchoolMapExtension() {
      
    }
    
    public SchoolMapExtension(ApexPages.StandardController stdController) {
        
        phasesFilter = new List<String>();
        fundingGroupFilter = new List<String>();
        fundingTypeFilter = new List<String>();  
        
        filterKeys = new Map<String, List<String>> {
                'Phase' => phasesFilter,
                'Funding Group' => fundingGroupFilter,
                'Funding Type' => fundingTypeFilter   
                };
                    
        createfilterMap();
        
        system.debug('filters-->' + filterKeys);
        
        //this.stdController = stdController; 
        org = (Organisation__c)stdController.getRecord();
        
        distance = 15;
        
        if(org != null) { 
            
            org = [SELECT Id, Phase__c, Phase_and_Funding_Group__c, Scheduled_to_Visit__c, Days_Since_Last_Visit__c , Visited_by_Ambassador__c, Funding_Group__c, School_Id__c, lat_long__c, Name,Latitude__c,Longitude__c, lat_long__Latitude__s, lat_long__Longitude__s FROM Organisation__c WHERE Id =: ApexPages.currentPage().getParameters().get('id')];
            orgLat = org.Latitude__c;
            orgLong = org.Longitude__c;
            currentOrgId = org.Id;
            phases = null;
            fundingGroups = null;
            
            listofSchools = [SELECT Id,School_Id__c, Days_Since_Last_Visit__c, Visited_by_Ambassador__c, Scheduled_to_Visit__c, Phase_and_Funding_Group__c, Funding_Group__c, Name, lat_long__c,lat_long__Latitude__s, lat_long__Longitude__s, Complete_Address__c, Phase__c, Phone_Number__c, Current_Movement_Category__c FROM Organisation__c WHERE Id =: ApexPages.currentPage().getParameters().get('id')]; 
            
        }
        
    }
 
    
    public void createfilterMap(){
        filterMap = new Map<String, List<SelectOption>>();
        List<SelectOption> options = new List<SelectOption>();
        
        for(String s : filterKeys.keyset()) {
            if(s == 'Phase') {
                options = new List<SelectOption>();
                
                Schema.DescribeFieldResult fieldResult = 
                Organisation__c.Phase__c.getDescribe();
                List<Schema.PicklistEntry> phaseList = fieldResult.getPicklistValues();
        
                for( Schema.PicklistEntry phase : phaseList) {
                    options.add(new SelectOption(phase.getLabel(), phase.getValue()));
                }
                
                filterMap.put('Phase', options);
  
            }
            
            if (s == 'Funding Group') {
                options = new List<SelectOption>();
                
                Schema.DescribeFieldResult fieldResult = 
                Organisation__c.Funding_Group__c.getDescribe();
                List<Schema.PicklistEntry> fgList = fieldResult.getPicklistValues();
        
                for( Schema.PicklistEntry fg : fgList) {
                    options.add(new SelectOption(fg.getLabel(), fg.getValue()));
                }
                
                filterMap.put('Funding Group', options);
                 
            }
            
        }
    }
    
}