src/objects/Proposal__c.object
<CustomObject>
    <description>Object used to store proposals that the Agency Sales team sends to their agencies.</description>
    <fields>
        <fullName>Booked_Premium_Amount__c</fullName>
        <label>Booked Premium Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Booked_Premium_Products__c</fullName>
        <label>Booked Premium Products</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contextual Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Featured Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Featured Job</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job of the week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsored Email Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsored Job</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Booked_Print_Ad_Size__c</fullName>
        <label>Booked Print Ad Size</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booked_Standard_Amount__c</fullName>
        <label>Booked Standard Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Booked_Standard_Products__c</fullName>
        <label>Booked Standard Products</label>
        <picklist>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Premium_Amount__c</fullName>
        <label>Proposed Premium Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_Premium_Products__c</fullName>
        <label>Proposed Premium Products</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contextual Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Featured Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Featured Job</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job of the week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsored Email Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsored Job</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Print_Ad_Size__c</fullName>
        <label>Proposed Print Ad Size</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_Standard_Amount__c</fullName>
        <label>Proposed Standard Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_Standard_Products__c</fullName>
        <label>Proposed Standard Products</label>
        <picklist>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Print</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Low</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Medium</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won - Premium</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateProposalWhenClosed.cls
@isTest
public class TestUpdateProposalWhenClosed {

    static testMethod void TestUpdateProposalWhenClosed() {
        
       
        //insert Proposal
        Proposal__c p = new Proposal__c (
            Name = 'TEST',
            Proposed_Standard_Amount__c = 900,
            Proposed_Premium_Amount__c = 1000,
            Proposed_Premium_Products__c = 'Featured Job',
            Proposed_Standard_Products__c = 'Gold',
            Proposed_Print_Ad_Size__c = '12 x 13',
            Stage__c = 'Proposal/Price Quote'
        );
        
        insert p;
         test.startTest();
        //update proposal           
        p.Stage__c = 'Closed Won - Low';
        
        update p;
        test.stopTest();
        
        //validate booking amounts and products are populated
        
        Proposal__c pr = [SELECT Booked_Print_Ad_Size__c, Booked_Standard_Amount__c,Booked_Premium_Amount__c, Booked_Premium_Products__c, Booked_Standard_Products__c
                         FROM Proposal__c WHERE Id =: p.Id];

        
        system.assertEquals(900, pr.Booked_Standard_Amount__c);
        system.assertEquals(1000, pr.Booked_Premium_Amount__c);
        system.assertEquals('Featured Job', pr.Booked_Premium_Products__c);
        system.assertEquals('Gold', pr.Booked_Standard_Products__c);
        system.assertEquals('12 x 13', pr.Booked_Print_Ad_Size__c);
            
    }
}